### PR TITLE
feat: ability to report with dynamic columns list

### PR DESCRIPTION
**Pull request by sclinede**
There was a problem in TableBuilder, that it treats block result as
current result row. Instead it MUST use instance variable defined in
builder for each row. And ther return that array as result.

### CODE REVIEW

**Comment by sclinede** [comment]
@isqad88 @artofhuman

**Comment by artofhuman** [comment]
looks good to me

**Comment by isqad** [comment]
nice

**Comment by sclinede** [comment]
@Napolskih

**Comment by Napolskih** [comment]
ок

**Pull request merged**
